server:
  port: 10086
  servlet:
    encoding:
      charset: UTF-8
    context-path: /@project.artifactId@
spring:
  profiles:
    active: @profiles.active@
  application:
    name: @project.parent.artifactId@
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #属性映射--开启驼峰命名
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: ["classpath*:/mapper/**/*.xml"]
